export const productCatalog = {
  ELECTRONICS: [
    "Smartphone",
    "Laptop",
    "Tablet",
    "Smartwatch",
    "Headphones",
    "Earbuds",
    "Bluetooth speaker",
    "Camera",
    "Television",
    "Monitor",
    "Keyboard",
    "Gaming console",
  ],
  CLOTHING: [
    "Shirt",
    "T-shirt",
    "Jeans",
    "Trousers",
    "Dress",
    "Jacket",
    "Shoes",
    "Saree",
    "Kurta",
    "Sportswear",
  ],
  FOOD: [
    "Restaurant meal",
    "Food delivery",
    "Snacks",
    "Coffee",
    "Dessert",
    "Groceries",
    "Health supplement",
  ],
  BEAUTY: [
    "Skin-care product",
    "Makeup",
    "Perfume",
    "Hair-care product",
    "Grooming device",
    "Salon treatment",
  ],
  ENTERTAINMENT: [
    "Streaming subscription",
    "Movie ticket",
    "Concert ticket",
    "Book",
    "Music subscription",
    "Online course",
  ],
  HOME: [
    "Furniture",
    "Home décor",
    "Kitchen appliance",
    "Cookware",
    "Bedding",
    "Lamp",
    "Cleaning appliance",
  ],
  TRAVEL: [
    "Flight ticket",
    "Train ticket",
    "Hotel stay",
    "Holiday package",
    "Travel bag",
    "Travel accessory",
  ],
  GAMING: [
    "Video game",
    "Gaming console",
    "Gaming mouse",
    "Gaming keyboard",
    "Controller",
    "In-game purchase",
    "Gaming subscription",
  ],
  ACCESSORIES: [
    "Watch",
    "Handbag",
    "Wallet",
    "Sunglasses",
    "Jewellery",
    "Belt",
    "Phone case",
  ],
  OTHER: [
    "Gift",
    "Fitness equipment",
    "Pet product",
    "Office supply",
    "Hobby item",
    "Household service",
  ],
};

export const productCategories = Object.keys(productCatalog);

export const productsForCategory = (category) =>
  productCatalog[category] || productCatalog.OTHER;
